name: render readme + docker

on:
  workflow_dispatch:
  push:
    branches:
      - "docker"
    paths:
      - 'README.Rmd'
      - '.github/workflows/render_readme.yml'
      - '.github/workflows/render_readme_docker.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  render-readme:
    runs-on: ubuntu-latest
    container: bahadzie/alpine-r:4.3.0
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4

      - name: Compile the readme
        run: |
          writeLines(
            knitr::knit_expand(
              "README.Rmd",
              packagename = read.dcf("DESCRIPTION", "Package"),
              institution = read.dcf("DESCRIPTION", "Config/Institution"),
              department = read.dcf("DESCRIPTION", "Config/Department"),
              department_url = read.dcf("DESCRIPTION", "Config/DepartmentURL"),
              recon = read.dcf("DESCRIPTION", "Config/Recon"),
              recon_description = read.dcf("DESCRIPTION", "Config/ReconDescription"),
              gh_repo = Sys.getenv("GITHUB_REPOSITORY")
            ),
            "README_expanded.Rmd"
          )
          rmarkdown::render(
            "README_expanded.Rmd",
            output_file = "README.md",
            output_dir = "."
          )
        shell: Rscript {0}


  commit-readme:
    needs: render-readme
    runs-on: ubuntu-latest
    steps:
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if ! git diff-index --quiet HEAD; then
            git add README.md
            # Also add README figures if they exist
            if [ -d man/figures ]
            then
              git add man/figures/
            fi
            git commit -m "Automatic readme update"
            git pull --rebase origin ${{ github.ref.name }}
            git push origin || echo "No changes to push"
          fi
        shell: bash {0}
